name: Checks

on:
  push:
    branches:
      - '*'

jobs:
  check:
    name: Check
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          skip-go-installation: true

      - name: Install golint
        run: go get golang.org/x/lint/golint

      - name: Run checks
        run: make check
